---
spring:
  profiles: peer2
  application: 
    name: api_gateway
  rabbitmq:
    host: localhost
    port: 5672
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASS}
server:
  port: 8086


eureka:
  instance:
    hostname: ${spring.application.name}-${server.port}
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/,http://localhost:8082/eureka/,http://localhost:8083/eureka/