---
spring:
  profiles: peer1
  application: 
    name: api_gateway
server:
  port: 8085


eureka:
  instance:
    hostname: ${spring.application.name}-${server.port}
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/,http://localhost:8082/eureka/,http://localhost:8083/eureka/